import Providers from '../components/(Context)/Providers';
import SideNav from '../components/(Navbar)/SideNav';
import './global.css';

export const metadata = {
  title: 'Welcome to weather-application',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="fixed h-screen w-full bg-gradient-to-br from-indigo-400 via-white to-blue-500">
        <Providers>
          <main>
            <div className="flex flex-col md:flex-row bg-background-feature h-[100vh] text-black">
                <SideNav />
                {children}
            </div>
          </main>
        </Providers>
      </body>
    </html>
  );
}
